name: Integration tests

on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * 1' # Weekly on Mondays at 6am UTC

env:
  ADAPT_AUTHORING_AUTH__tokenSecret: 'test-auth-secret-for-ci'
  ADAPT_AUTHORING_MONGODB__connectionUri: 'mongodb://0.0.0.0/adapt-authoring-integration-test'
  ADAPT_AUTHORING_SERVER__host: 'localhost'
  ADAPT_AUTHORING_SERVER__port: '5678'
  ADAPT_AUTHORING_SERVER__url: 'http://localhost:5678'
  ADAPT_AUTHORING_SESSIONS__secret: 'test-sessions-secret-for-ci'
  CUSTOM_REPO: adapt-security/adapt-authoring-integration-data

jobs:
  default:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [24.x]
        mongodb-version: [8.0]
    steps:
    - uses: actions/checkout@v4
      with:
        persist-credentials: false

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.10.0
      with:
        mongodb-version: ${{ matrix.mongodb-version }}

    - name: Install dependencies
      run: npm ci --legacy-peer-deps

    - name: Download custom test data
      run: gh repo clone ${{ env.CUSTOM_REPO }} custom
      env:
        GH_TOKEN: ${{ github.token }}

    - name: Run integration tests
      run: npx at-integration-test
      env:
        CUSTOM_DIR: ${{ github.workspace }}/custom
